Changed classes api internal to public and fx stream allMarkPrice
JKorf/Binance.Net pull request #1192
Opened 2023-01-26 13:13 UTC by VozyakovAV

1. Changed classes api internal to public
This was necessary so that I could inherit classes.

2. fx stream allMarkPrice
added subcribe to allMarkPrice for CoinFutures

2023-02-04 06:21 UTC, HypsyNZ approved these changes
Looks good to me

2023-02-04 06:22 UTC, HypsyNZ approved these changes
Looks good to me

2023-02-04 06:22 UTC, HypsyNZ approved these changes
Looks good to me

2023-03-10 09:08 UTC, HypsyNZ commented on Binance.Net/Binance.Net.csproj
> +    <PackageId>VozyakovAV.Binance.Net</PackageId>
Change this

2023-03-10 09:14 UTC, HypsyNZ requested changes
Changes are required

2023-03-10 10:29 UTC, VozyakovAV commented on Binance.Net/Binance.Net.csproj
> +    <PackageId>VozyakovAV.Binance.Net</PackageId>
Fixed, sorry.

2023-03-13 13:14 UTC, HypsyNZ approved these changes
Thank you

2023-03-18 13:44 UTC, JKorf commented
I'd rather not make those classes public. It can be confusing for people to see those types when theyre new to the library, so I'd rather only make classes public which are actually usable

2023-04-17 18:34 UTC, closed without merging