Added convert endpoints
JKorf/Binance.Net pull request #1322
Opened 2023-11-24 23:53 UTC by Owdares

Added convert endpoints

Info - https://binance-docs.github.io/apidocs/spot/en/#convert-endpoints

2023-11-25 03:06 UTC, Owdares commented
Perhaps GetConvertListAllPairsAsync() should be moved to ExchangeData...

2023-12-02 21:25 UTC, JKorf requested changes

2023-12-02 21:25 UTC, JKorf commented on Binance.Net/Enums/ConvertOrderStatus.cs
> +        [Map("PROCESS")]
The idea of this attribute is that you can use the EnumConverter for deserialization. So I think the `ConvertOrderStatusConverter` isn't needed

2023-12-03 10:39 UTC, JKorf commented
Thanks for the work :)

2023-12-03 10:40 UTC, merged