add agent endpoints
JKorf/Binance.Net pull request #1450
Opened 2024-12-05 08:45 UTC by Alex1911-Jiang

2024-12-05 08:48 UTC, Alex1911-Jiang commented
Docs: https://binance-docs.github.io/apiAgent-API-EN/api_rebate_endpoints_spot_EN/

2024-12-05 08:49 UTC, Alex1911-Jiang commented
Sorry, I only added the endpoints that I need to use.

2024-12-05 10:05 UTC, JKorf requested changes

2024-12-05 10:05 UTC, JKorf commented on Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiAgent.cs
> +        public async Task<WebCallResult<BinanceIfNewUser>> IfNewUser(string apiAgentCode, int? receiveWindow = null, CancellationToken ct = default)
Same comments

2024-12-05 10:05 UTC, JKorf commented on Binance.Net/Enums/IfNewUserMarginedFuturesType.cs
> +        USDT_margined_Futures = 1,
Use CamelCasing please, so `UsdtMarginedFutures`

2024-12-05 10:05 UTC, JKorf commented on Binance.Net/Interfaces/Clients/UsdFuturesApi/IBinanceRestClientUsdFuturesApiAgent.cs
> +    /// Binance USD-M futures account endpoints, query user data.
Incorrect comment

2024-12-05 10:05 UTC, JKorf commented on Binance.Net/Interfaces/Clients/CoinFuturesApi/IBinanceRestClientCoinFuturesApiAgent.cs
> +    /// Binance Coin futures account endpoints, query user data.
Incorrect comment

2024-12-05 10:05 UTC, JKorf commented on Binance.Net/Objects/Models/Futures/BinanceIfNewUser.cs
> +        public bool ifNewUser { get; set; } = false;
`IfNewUser`, also default values not needed for bool values as the default is already `false`

2024-12-05 10:05 UTC, JKorf commented on Binance.Net/Objects/Models/Spot/BinanceIfNewUser.cs
> +        public bool ifNewUser { get; set; } = false;
See other model

2024-12-05 10:06 UTC, JKorf commented
Please have a look at the comments

2024-12-05 14:33 UTC, Alex1911-Jiang commented
I made some modifications, but "rate limiter" doesn't seem to be in the documentation, except for weight.

2024-12-09 08:10 UTC, JKorf requested changes

2024-12-09 08:10 UTC, JKorf commented on Binance.Net/Clients/CoinFuturesApi/BinanceRestClientCoinFuturesApiAgent.cs
> +            parameters.AddOptional("brokerId", brokerId);
You removed the `ToString`, but it still should be `parameters.Add` instead of `parameters.AddOptional`

2024-12-09 08:10 UTC, JKorf commented on Binance.Net/Clients/UsdFuturesApi/BinanceRestClientUsdFuturesApiAgent.cs
> +            parameters.AddOptional("brokerId", brokerId.ToString(CultureInfo.InvariantCulture));
Same, you also still have the ToString here

2024-12-09 08:10 UTC, JKorf commented
> I made some modifications, but "rate limiter" doesn't seem to be in the documentation, except for weight.

I see, it's not really clear what the limits are so I guess this is good enough. 

2 more small comments.

2024-12-10 03:19 UTC, Alex1911-Jiang commented
Done!

2024-12-10 07:40 UTC, merged